title: RDF Portal
description: RDFポータルサイトのリニューアル
baseurl: "/rdf-portal-v2.github.io" # GitHub Pagesのサブディレクトリ
url: "https://penqeinc.github.io" # GitHub Pagesのベース URL
theme: minima
plugins:
  - jekyll-feed

# Navigation menu
header_pages:
  - index.md
  - endpoints.md
  - datasets.md
  - statistics.md
  - documents.md
  - search.md
  - about.md
